services:
  client:
    image: nginx:stable-alpine3.17-slim
    volumes:
      - ./client/index.html:/usr/share/nginx/html/index.html:ro
      - ./client/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

  proxy:
    build:
      context: proxy-server
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS="-Xms50M -Xmx50M"
      - SPRING_SERVLET_MULTIPART_ENABLED=true

  destination:
    build:
      context: proxy-server
    environment:
      - JAVA_OPTS="-Xms50M -Xmx50M"
      - SPRING_SERVLET_MULTIPART_ENABLED=true
    ports:
      - "9000:8080"

